BikeRentalSystem/BikeRentalSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BikeUsers.urls')),
    path('operators/', include('BikeOperators.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

BikeRentalSystem/BikeUsers/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    path('', view=home, name='CustomerHome'), # Home Page
    path('register/', view=SignUpView.as_view(), name='CustomerRegister'), # User Registration
    # path('login/', view=SignIn.as_view(), name='CustomerLogin'), # User Login
    path('accounts/login/', view=SignIn.as_view(), name='CustomerLogin'), # User Login
    path('logout/', view=auth_view.LogoutView.as_view(template_name='BikeUsers/login.html'), name='CustomerLogout'), # User Logout
    path('update_customer/', CustomerUpdateView, name="ProfileUpdate"), # User Profile Update
    path('login_success/', login_success, name='login_success'),

    path('bike/<int:pk>/',view=Bikedetails.as_view(),name='ShowBikeDetails'), # Show Bike Details
    path('history/', view_bike_history, name='ViewBikeHistory'), # Bike Rent History Page
    path('payment/',view=MakePayment, name='Payment'), # Bike Payment Page
    path('check_bikes/', check_bikes, name='CheckBikes'), # Supporting function to check available bikes
    path('viewbike/<int:pk>/',bikeinfo, name='ViewBikes'), # View Available Bikes of Selected Station

    path('feedback/<int:pk>/', view=Rettingadd, name='BikeFeedback'), # Feedback Page
    
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='BikeUsers/password/password_reset.html'), name='password_reset'), # Password Reset Page

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='BikeUsers/password/password_reset_done.html'), name='password_reset_done'), # Password Mail Sent Page
    
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='BikeUsers/password/password_reset_confirm.html'), name='password_reset_confirm'), # Password Reset Confirm Page
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='BikeUsers/password/password_reset_complete.html'),name='password_reset_complete'), # Password Complete Page
    
    path('update_password/', view=PasswordChangeView, name='PasswordUpdate'), # To update password

    path('search_city/', view=search_city, name='SearchCity'), # Supporting function to get all citites of selected state
    path('search_station/', view=search_station, name='SearchStation'), # Supporting function to get all station names
    path('get_map/<int:pk>/', view=get_map, name='GetMap'), # Supporting function to get location details of selected station
]

BikeRentalSystem/BikeUsers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class State(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    state = models.ForeignKey(to=State, on_delete=models.CASCADE)
    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name 


class Customer(AbstractUser):
    STATUS_CHOICES = [('P', 'Pending'), ('V', 'Verified')]
    USER_CHOICES = [('C', 'Customer'), ('O', 'Operator')]
    first_name = models.CharField(max_length=50, help_text='Enter your first name')
    last_name = models.CharField(max_length=50, help_text='Enter your last name')
    email = models.EmailField(help_text='Enter your email id', unique=True)
    contact = models.IntegerField(help_text='Enter your contact number', null=True)
    address = models.CharField(max_length=200, help_text='Enter your address', null=True)
    pincode = models.IntegerField(help_text='Enter your pincode', null=True)
    proof = models.ImageField(upload_to='customer_proofs', help_text='Enter your identity proof', null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='P')
    role = models.CharField(('Select Your Role'), choices=USER_CHOICES, max_length=1, help_text='Select your role', null=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True, help_text='Select your state') 
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, help_text='Select your city')

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} ({self.email})"


class Station(models.Model):
    name = models.CharField(verbose_name="Name",max_length=100)
    address = models.CharField(verbose_name="Address",max_length=500, unique=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, help_text='Select your city')
    post_code = models.CharField(verbose_name="Post Code",max_length=8)
    country = models.CharField(verbose_name="Country",max_length=100)	
    longitude = models.CharField(verbose_name="Longitude", max_length=50)
    latitude = models.CharField(verbose_name="Latitude", max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return f'{self.name}, {self.city} ({self.post_code})'


class bike(models.Model):
    BIKE_STATUS_CHOICES = [('A', 'Available'), ('R', 'On Rent')] 
    operatorid = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, help_text='Enter operator id')
    bikename = models.CharField(max_length=50, help_text='Enter bike name', verbose_name='Name of Bike')
    brandname = models.CharField(max_length=50, help_text='Enter bike brand name', verbose_name='Brand Name')
    price_hr = models.PositiveIntegerField(help_text='Enter bike price per hour', verbose_name='Price Per Hour')
    price_day = models.PositiveIntegerField(help_text='Enter bike price per day', null=True, verbose_name='Price Per Day')
    registered_no = models.CharField(max_length=50, help_text='Enter bike registered number', verbose_name='Bike Registration Number', unique=True)
    bike_image=models.ImageField(upload_to='bike_image', help_text='Add bike image', null=True)
    bike_manufactured_date=models.DateField(help_text='Add Manufactured date of bike')
    bikecolor = models.CharField(max_length=50, help_text='Enter bike color', verbose_name='Bike Color')
    bikestatus = models.CharField(choices=BIKE_STATUS_CHOICES, max_length=1, default='A', verbose_name='Select Bike Status')
    station_id = models.ForeignKey(Station, on_delete=models.CASCADE, verbose_name='Select Station Location', help_text='Select Station Location')
    
    def __str__(self) -> str:
        return f" {self.bikename} ({self.brandname})"


class Rating(models.Model):
    suggestions=models.CharField(max_length=50, help_text='Enter your suggestion', default='Good')
    star = models.IntegerField(help_text='Add ratings')
    bike = models.ForeignKey(bike, on_delete=models.CASCADE, help_text='Select Bike', default=None)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    def __str__(self):
        return f'{self.suggestions} - {self.star} stars'


class Payment(models.Model):
    PAYMENT_CHOICES = [('COD', 'Cash On Delivery')]
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, null=True, related_name='customer+')
    operator = models.ForeignKey(Customer, on_delete=models.PROTECT, null=True, related_name='operator+')
    bike = models.ForeignKey(bike, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    datetime = models.DateTimeField(auto_now_add=True)
    mode = models.CharField(choices=PAYMENT_CHOICES, max_length=3)

    def __str__(self) -> str:
        return f'{self.customer.first_name} paid - {self.amount} ({self.mode}) on {self.datetime} for bike {self.bike.bikename} of {self.operator.first_name}'


class BikeRentHistory(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, null=True, related_name='customer+')
    operator = models.ForeignKey(Customer, on_delete=models.PROTECT, null=True, related_name='operator+')
    from_date_time = models.DateTimeField(verbose_name='Select From Date Time:')
    to_date_time = models.DateTimeField(verbose_name='Select To Date Time:')
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    bike = models.ForeignKey(bike, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.customer.first_name} rented {self.bike.bikename} - from {self.from_date_time} to {self.to_date_time} at {self.payment.amount} rupees'

BikeRentalSystem/BikeUsers/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm

'''User Registration Form'''
class CustomerCreationForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ['role','first_name', 'last_name', 'username', 'contact', 'address', 'pincode', 'email', 'proof', 'state', 'city']

    def __init__(self, *args, **kwargs):
        super(CustomerCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

'''User Login Form'''
class CustomerLoginForm(AuthenticationForm):
    username = forms.CharField(help_text='Enter your username', required=True)

    class Meta:
        model = Customer
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(CustomerLoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


'''Customer Change Form'''
class CustomerChangeForm(UserChangeForm):
    class Meta:
        model = Customer
        exclude = ('status', )


'''Select City Form'''
class CityForm(forms.ModelForm):
    CHOICES = (
        ("", "---------"),
    )

    name = forms.ChoiceField(required=True, choices=CHOICES, label="City", widget=forms.Select(attrs={'class': 'form-control'}))
    states = State.objects.all()
    state = forms.ModelChoiceField(queryset=states, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = City
        fields = ['state', 'name']

'''Customer Change Form'''
class CustomerUpdateForm(UserChangeForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'username', 'contact', 'address', 'pincode', 'email', 'proof', 'state', 'city']

    def __init__(self, *args, **kwargs):
        super(CustomerUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class PasswordUpdateForm(PasswordChangeForm):
    class Meta:
        model = Customer

    def __init__(self, user, *args, **kwargs):
        super(PasswordUpdateForm, self).__init__(user, *args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

BikeRentalSystem/BikeUsers/templates/BikeUsers/BikeDetails.html
{% extends 'BikeUsers/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock css %} {% block content %}

<div class="card mt-5">
    <div class="row g-0">
        <div class="col-md-6">
            <img src="{{ object.bike_image.url }}" class="img-fluid rounded-start" alt="{{ object.bikename }}"
                style="margin-left: 50px;">
        </div>
        <div class="col-md-6">
            <div class="card-body mt-5">
                <h2 class="card-title">{{ object.bikename }} ({{ object.brandname }})</h2>
                <h5 class="card-text mt-2">Price Per Hour: &#8377;{{object.price_hr}}</h5>
                <h5 class="card-text">Registration Number: {{object.registered_no}}</h5>
                <h5 class="card-text">Price Per Day: &#8377;{{object.price_day}}</h5>
                <h5 class="card-text">Manufacturing Date: {{object.bike_manufactured_date}}</h5>
                <h5 class="card-text">Color: {{object.bikecolor}}</h5>
                <h5 class="card-text">Status: {{object.get_bikestatus_display}}</h5>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

BikeRentalSystem/BikeUsers/templates/BikeUsers/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/ico"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> {% block css %} {% endblock css %}
    <title>Bike Rental System</title>
</head>

<body>
    <img id="loading" alt="Loading..." src="{% static 'images/loading.gif' %}" />
    <nav class="navbar navbar-expand-lg navbar-light bg-light my-loader">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'CustomerHome' %}">
                <img src="{% static 'images/logo.jpg' %}" alt="Bike Rental System" width="30" height="24" class="d-inline-block align-text-top"> BikeRentalSystem
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'CustomerHome' %}">Home</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ViewBikeHistory' %}">Rent History</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ProfileUpdate' %}">Update Profile</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'PasswordUpdate' %}">Update Password</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'CustomerLogout' %}">Sign out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'CustomerLogin' %}">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'CustomerRegister' %}">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_reset' %}">Reset Password</a>
                    </li>
                    {% endif %}

                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container my-loader">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-2" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %} {% endif %} {% block content %} {% endblock content %}
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $('.my-loader').css("opacity", 0);
        $(document).ready(function () {
            $("#loading").hide();
            $('.my-loader').css("opacity", 1);
        });
        
    </script>

    {% block js %} {% endblock js %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
</body>

</html>

BikeRentalSystem/BikeUsers/templates/BikeUsers/bikeadd.html
{% extends 'BikeUsers/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> {% endblock css %} {% block content %}

<form class="row g-3 mt-2 needs-validation form-center" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <h1 class="text-center">Add/Update Bike Details</h1>
    <div class="col-md-6">

        <!-- To print any error for form validation -->
        {% if form.errors %} {% for field in form %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endif %}

        <!-- Printing Form fields -->
        {% for field in form %}
        <div class="col-md-12">
            <label for="{{ field.id_for_label }}" class="form-label mt-2">{{ field.label_tag }}</label> {{ field }}
            <div class="valid-feedback mt-2">
                Looks good!
            </div>

            <div class="invalid-feedback">
                {{ field.help_text }}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="form-center">
        <button class="btn btn-primary mb-2 " type="submit">Submit</button>
    </div>
</form>

{% endblock content %} {% block js %}
<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock js %}

BikeRentalSystem/BikeUsers/templates/BikeUsers/feedback.html
{% extends 'BikeUsers/base.html' %} {% load static %} {% load crispy_forms_tags %} {% block css %}
<link rel="stylesheet" href="{% static 'css/style1.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"> {% endblock css %}
{% block content %}
<h1 class="text-center mt-2">Please Provide Your Feedback</h1>
<div class="stars">
    <form method="POST" class="row g-3 mt-2 needs-validation form-center">
        {% csrf_token %}
        <div class="container-fluid">
            <input class="star star-5" id="star-5" type="radio" name="star" value="5" />
            <label class="star star-5" for="star-5"></label>
            <input class="star star-4" id="star-4" type="radio" name="star" value="4" />
            <label class="star star-4" for="star-4"></label>
            <input class="star star-3" id="star-3" type="radio" name="star" value="3" />
            <label class="star star-3" for="star-3"></label>
            <input class="star star-2" id="star-2" type="radio" name="star" value="2" />
            <label class="star star-2" for="star-2"></label>
            <input class="star star-1" id="star-1" type="radio" name="star" value="1" />
            <label class="star star-1" for="star-1"></label>

            <textarea class="form-control mb-3" placeholder="Leave your suggestions here" name="suggestions" style="height: 100px; width: 450px;"></textarea>

            <input type="submit" name="submit" class="btn btn-primary" />
        </div>
    </form>
</div>
{% endblock content %}


{% block js %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock js %}

BikeRentalSystem/BikeUsers/templates/BikeUsers/get_map.html
{% extends 'BikeUsers/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}
{% block content %}

{{ station|json_script:"data" }}

<div class="row">
    <div id='routeInfoPanel'></div>
    <div class="col-md-4" id='directionsItinerary'></div>
    <div class="col-md-8" id="myMap"></div>
</div>
{% endblock content %}

{% block js %}
<!-- define required variables in template -->

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/get_map.js' %}"></script>

<script type='text/javascript'
    src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AoCKO8_fba-FuLiqndRFZjJCyLW6_xi7ABuWX_PJFzffKtBFStyV5kPFPTWK-ADu'
    async defer></script>

<script id="data" type="application/json"></script>
{% endblock js %}

BikeRentalSystem/BikeUsers/templates/BikeUsers/index.html
{% extends 'BikeUsers/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock css %} {% block content %}
<!-- To print warning/success alert -->

{% if user.is_authenticated %}
<h1>Welcome, {{user.username}}! </h1>
{% endif %} {{ stations|json_script:"data" }}

<div class="btn-group my-3 form-center" role="group" aria-label="Basic outlined example">
    <button type="button" class="btn btn-outline-primary" id="mapSearch">Search by Maps</button>
    <button type="button" class="btn btn-outline-primary" id="pincodeSearch">Search by Pincode</button>
    <button type="button" class="btn btn-outline-primary" id="citySearch">Search by City</button>
</div>


<!-- Showing form for pincode search start-->
<div id="searchOutput" class="form-center">
    <form method='POST' class="col-md-12 my-3 form-center" id='pinCodeForm' style="display: none;">
        {% csrf_token %}
        <input type='text' min=6 max=6 name='pincodeText' id='pincodeText' class="form-control mx-3" placeholder="Enter Pincode" autocomplete="off" required>

        <input type='submit' class="btn btn-warning" id='pincodeBtn' name='pincodeBtn' value="Search">
    </form>
</div>
<!-- Showing form for pincode search end -->

<!-- Showing form for city search start -->

<div class="container mb-3 col-md-12" id="CityForm" style="display: none;">
    <form class="row col-md-12" method="post" id="mapsform">
        {% csrf_token %} {{form}}
    </form>
</div>

<!-- Showing form for city search end -->

<!-- Showing form for maps search start -->

<div id='searchBoxContainer' style="display: none;">
    <label for="searchLabel" class="form-label">Search Location:</label>
    <input type='text' id='searchBox' class="form-control mb-3" placeholder="Start typing location..." autocomplete="off" />
</div>
<!-- Showing form for maps search end -->


<!-- Result of search for pincode and city by search start -->
<table class="table table-striped table-hover caption-top" id='stationTable' style="display: none;">
    <caption>List of stations</caption>
    <thead>
        <tr>
            <th scope="col">SR No.</th>
            <th scope="col">Name of Station</th>
            <th scope="col">Pincode</th>
            <th scope="col">Address</th>
            <th scope="col">Directions</th>
            <th scope="col">Bikes</th>
        </tr>
    </thead>
    <tbody id='tbody'>
    </tbody>
</table>
<!-- Result of search for pincode and city by search end -->

<!-- Showing stations on map start -->
<div id="myMap" style="position:relative;width:1300px;height:600px;" class="mb-3"></div>
<!-- Showing stations on map end -->

{% endblock content %} {% block js %}
<!-- define required variables in template -->
<script>
    var URL = "{% url 'SearchStation' %}";
    var URL1 = "{% url 'SearchCity' %}";
</script>
<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/home.js' %}"></script>

<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=AoCKO8_fba-FuLiqndRFZjJCyLW6_xi7ABuWX_PJFzffKtBFStyV5kPFPTWK-ADu&callback=loadMapScenario' async defer></script>

<script id="data" type="application/json"></script>
{% endblock js %}

BikeRentalSystem/BikeUsers/templates/BikeUsers/maps.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />

    <!-- Reference to the Bing Maps SDK -->
    <script type='text/javascript'
            src='http://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AoCKO8_fba-FuLiqndRFZjJCyLW6_xi7ABuWX_PJFzffKtBFStyV5kPFPTWK-ADu' 
            async defer></script>
    
    <script type='text/javascript'>
    function GetMap()
    {
        var map = new Microsoft.Maps.Map('#myMap');

        //Add your post map load code here.
    }
    </script>
</head>
<body>
    <div id="myMap" style="position:relative;width:1500px;height:750px;"></div>
</body>
</html>

BikeRentalSystem/BikeUsers/templates/BikeUsers/view_bike_history.html
{% extends 'BikeUsers/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}
{% block content %}

<div class="container mt-2">
    <h1 class="text-center">Your Bike Rent History</h1>
    {% if histories %}
    {% for history in histories %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-3">
                <img src="{{ history.bike.bike_image.url }}" class="img-fluid rounded-start" alt="{{ history.bike.bikename }}" height="200px" width="230px">
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h4 class="card-title">Bike: {{ history.bike.bikename }}</h4>
                    <p class="card-text">From: {{ history.from_date_time }}</p>
                    <p class="card-text">To: {{ history.to_date_time }}</p>
                    <p class="card-text"><strong>Paid: &#8377;{{history.payment.amount}} via {{ history.payment.get_mode_display }} on {{ history.payment.datetime }}</strong></p>
                    <a href="{% url 'BikeFeedback' history.bike.id %}" class="btn btn-md btn-success">Give Feedback</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4 class="text-center mt-3">No Bike Rent History Found! <small><a href="{% url 'CustomerHome' %}"> Book Your Bike Here!</a></small> </h4>
    {% endif %}
</div>
{% endblock content %}